### ISSUE TITLE
Looks cool. What license is it under? 

### ISSUE THREAD

**Issue by mgifford** [colbyfayock/imagecarbon#3]
I assume you've got this under the Apache 2, following what CO.js does

https://github.com/thegreenwebfoundation/co2.js

They provide a pretty good example to follow.

**Comment by colbyfayock** [comment]
thanks @mgifford! didnt even consider adding a license for this since it was a web project. i typiecally use MIT for my projects. ill go ahead and add one :) thanks for asking!

edit: went with Apache because i wasn't sure about the name being completely open to use (based on my limited understanding from reading the explanation here on GitHub)
